CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    avatar VARCHAR(255),
    account_type VARCHAR(50),
    onboarding_completed BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE json_resources (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_name VARCHAR(255) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    json_payload TEXT NOT NULL,
    CONSTRAINT uk_json_resources_collection_resource UNIQUE (collection_name, resource_id)
);
